image: tmaier/docker-compose:latest
services:
  - docker:dind

before_script:
  - docker info
  - docker-compose --version
stages:
  - build
  - test
  - deploy
variables:
  POSTGRESQL_HOST: "postgres"
  POSTGRESQL_PORT: "6379/1"
  POSTGRESQL_PASSWORD: "inkpassword"
  POSTGRESQL_USERNAME: "postgres"
  REDIS_HOST: "redis"
  SECRET_KEY_BASE: "f89c3d1e35cd199ddd4b6d55318de7ce30c9451c27019394bab96a1acc90acb677578bc284b9a0bb53f010952594a2f544b196fb9a18d6019ec37d99f1eaf245"
  TEST_SECRET_KEY_BASE: "83dcb9140c078bd7d5a381be700e34b99de33ddf1b5d7f92ba5df356afc7f419bcc605a978649c6d639fe100f05ff721a1a482a7c1e0df416d904eef7a1acee9"
  DEVELOPMENT_SECRET_KEY_BASE: "943d29212a265d6d7781b07f2850dde8b5b1bb72c2b713e2f72c74322d24f06a0da6276c8e88d454c976641fe410d9cc0fc4fd5ad7f2169dbb3593cc117e9d33"
  DEVELOPMENT_FILE_LOCATION: "./ink_api_files/"
  TEST_FILE_LOCATION: "/tmp/ink_api_files/"
  PRODUCTION_FILE_LOCATION: "./ink_api_files/"

build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.inkmap.com:5000
    - docker build -t registry.inkmap.com:5000/devops/ink-api .
    - docker push registry.inkmap.com:5000/devops/ink-api
test:
  stage: test
  script:
    - mv .env.sample .env
    - mv docker/docker-compose-test.yml docker-compose-test.yml
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.inkmap.com:5000
    - /bin/sh docker/ci-test.sh
deploy:
  variables:
    RANCHER_ACCESS_KEY: $RANCHER_ACCESS_KEY
    RANCHER_SECRET_KEY: $RANCHER_SECRET_KEY
    RANCHER_URL: $RANCHER_URL
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
    - upgrade
