services:
  - postgres:latest

stages:
  - build
  - review

variables:
  IMAGE_ORG: inkcoko
  IMAGE_NAME: ink-api
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ''
  BASE_DOMAIN: gateway.ps.semioticsquares.com
  CONFIGURATION_REPOSITORY: https://gitlab.coko.foundation/INK/deployment-config.git

build:
  image: docker:latest
  stage: build
  script:
    - docker version
    - docker build -t $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA .
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then exit 0; fi
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - echo "Ignore warning! Cannot perform an interactive login from a non TTY device"
    - docker push $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA

review:
  image: pubsweet/deployer:c3e772e738758166eb065f0c96690a75a02bc39b
  stage: review
  environment:
    name: staging
    # !! kube-lego will fail if domain > 63 chars
    url: "https://${CI_ENVIRONMENT_SLUG}.${BASE_DOMAIN}"
    on_stop: stop_review
  except:
    - master
  script:
    - source deploy.sh
    - create_deployment

stop_review:
  image: pubsweet/deployer:latest
  stage: review
  variables:
    GIT_STRATEGY: none
  environment:
    name: staging
    action: stop
  when: manual
  except:
    - master
  script:
    - source deploy.sh
    - delete_deployment
    - delete_objects_in_environment pvc
