services:
  - postgres:latest

stages:
  - build
  - staging

variables:
  IMAGE_ORG: inkcoko
  IMAGE_NAME: ink-api
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ''
  BASE_DOMAIN: gateway.ps.semioticsquares.com
  CONFIGURATION_REPOSITORY: https://gitlab.coko.foundation/INK/deployment-config.git

build:
  image: docker:latest
  stage: build
  script:
    - docker version
    - docker build -t $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA .
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then exit 0; fi
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - echo "Ignore warning! Cannot perform an interactive login from a non TTY device"
    - docker push $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA

staging:
  image: pubsweet/deployer:latest
  stage: staging
  environment:
    name: staging/${CI_COMMIT_REF}
    # !! kube-lego will fail if domain > 63 chars
    url: "https://${CI_ENVIRONMENT_SLUG}.${BASE_DOMAIN}"
  except:
    - master
  script:
    - source deploy.sh
    - create_deployment
