services:
  - postgres:latest

stages:
  - build
  - test
  - review

variables:
  IMAGE_ORG: inkcoko
  IMAGE_NAME: ink-api
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ''
  BASE_DOMAIN: gateway.ps.semioticsquares.com
  CONFIGURATION_REPOSITORY: https://gitlab.coko.foundation/INK/deployment-config.git

build:
  image: docker:latest
  stage: build
  script:
    - docker version
    - docker build -t $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA .
    - if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_PASSWORD" ]; then exit 0; fi
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - echo "Ignore warning! Cannot perform an interactive login from a non TTY device"
    - docker push $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA

test:
  image: $IMAGE_ORG/$IMAGE_NAME:$CI_COMMIT_SHA
  stage: test
  variables:
    GIT_STRATEGY: none
    POSTGRESQL_HOST: postgres
    POSTGRESQL_PORT: '5432'
    POSTGRESQL_USERNAME: postgres
    TEST_SECRET_KEY_BASE: "83dcb9140c078bd7d5a381be700e34b99de33ddf1b5d7f92ba5df356afc7f419bcc605a978649c6d639fe100f05ff721a1a482a7c1e0df416d904eef7a1acee9"
    TEST_FILE_LOCATION: '/tmp/ink_api_files/'
    RAILS_ENV: test
  script:
    - cd /app
    - ./bin/rake db:create
    - ./bin/bundle exec rspec spec

review:
  image: pubsweet/deployer:b12456b7fb6f18edc2399d304ba016d2fc451978
  stage: review
  environment:
    name: review/$CI_COMMIT_REF_NAME
    # !! kube-lego will fail if domain > 63 chars
    url: "https://${CI_ENVIRONMENT_SLUG}.${BASE_DOMAIN}"
    on_stop: stop_review
  except:
    - master
  script:
    - source deploy.sh
    - ensure_deploy_variables
    - clone_config_repo
    - create_kubeconfig
    - ensure_namespace
    - generate_objects

stop_review:
  image: pubsweet/deployer:latest
  stage: review
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  when: manual
  except:
    - master
  script:
    - source deploy.sh
    - delete_deployment
    - delete_objects_in_environment pvc
