version: '2'
services:
  postgres:
    image: 'postgres:9.5'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis/data
  ink:
    build: .
    links:
      - postgres
      - redis
    volumes:
      - ./:/ink-api
    env_file:
      - '.env'
    depends_on:
      - postgres
  sidekiq:
    build: .
    command: '/bin/sh docker/init_sidekiq.sh'
    env_file:
      - '.env'
    links:
      - postgres
      - redis
    volumes:
      - ./:/ink-api
    depends_on:
      - ink
  slanger:
    image: antillion/slanger
    ports:
      - 4567:4567
      - 8080:8080
    links:
      - redis:redis
    env_file:
      - '.env'
  # editoria:
  #   image: inkmap/editoria:0.1.2
  #   volumes:
  #     - ./editoria/api/db/production:/editoria/api/db/production
  #   environment:
  #     PUBSWEET_SECRET: 5046a3dd-d178-41ac-bd87-cac327cdf23a
  #     INK_ENDPOINT: http://ink:3000
  #     INK_USERNAME: admin@admin.com
  #     INK_PASSWORD: abc12345
  #   links:
  #     - ink:ink
  #   ports:
  #     - "3000:3000"
    # depends_on:
    #   - setupdb
  # setupdb:
  #   image: inkmap/editoria:0.1.2
  #   volumes:
  #     - ./editoria/api/db/production:/editoria/api/db/production
  #   environment:
  #     PUB_USER: admin
  #     PUB_MAIL: admin@inkmap.com
  #     PUB_PASS: 12345
  #     PUB_COL: Collection
  #   command: sh docker/setupdb
