version: '3'

services:
  postgres:
    image: postgres:9.5

  ink:
    build: .
    env_file:
      - '.env.sample'
    environment:
      - RAILS_ENV=test
    entrypoint: ['./bin/wait-for-it', 'postgres:5432', '-s', '-t', '40', '--', './bin/test']
