version: '2'
services:
  postgres:
    image: 'postgres:9.5'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis/data
  web:
    build: .
    links:
      - postgres
      - redis
    volumes:
      - ./:/ink-api
    env_file:
      - '.env'
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  sidekiq:
    build: .
    command: '/bin/sh docker/init_sidekiq.sh'
    env_file:
      - '.env'
    links:
      - postgres
      - redis
    volumes:
      - ./:/ink-api
    depends_on:
      - web
