version: '2'
services:
  postgres:
    image: 'postgres:9.5'
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis/data
  ink:
    build: .
    links:
      - postgres
      - redis
      - slanger
    env_file:
      - '.env'
    depends_on:
      - postgres
      - slanger
    ports:
      - "3000:3000"
  slanger:
    image: inkmap/slanger:1.0.3
    ports:
      - 4567:4567
      - 8080:8080
    links:
      - redis:redis
    env_file:
      - '.env'
volumes:
  db: {}
  gems:
    # Flagging this as "external" means it will use the volume named "gems" on the host instead of making a new volume specific to this docker-compose file
    external: true
