version: '3'

services:
  postgres:
    image: postgres:9.5
    ports:
      - 5432:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis-volume:/var/lib/redis/data

volumes:
  redis-volume:
  postgres-volume:
  ink-api-files-volume:
