# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 50 } %>
  host: <%= ENV.fetch('POSTGRESQL_HOST', 'localhost') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', '') %>
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', 'postgres') %>

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRESQL_DB_NAME', 'ink_production') %>

staging:
  <<: *default
  database: <%= ENV.fetch('POSTGRESQL_DB_NAME', 'ink_staging') %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRESQL_DB_NAME', 'ink_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRESQL_DB_NAME', 'ink_test') %>
