# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 50 } %>
  host: <%= ENV.fetch('POSTGRESQL_HOST', 'localhost') %>
  password: <%= ENV.fetch('POSTGRESQL_PASSWORD', '') %>
  username: <%= ENV.fetch('POSTGRESQL_USERNAME', 'postgres') %>

production:
  <<: *default
  database: ink_production

staging:
  <<: *default
  database: ink_staging

development:
  <<: *default
  database: ink_development

test:
  <<: *default
  database: ink_test
