# If you are going to change this,
# you should move the contents of the old storage directory to the new one
# so that process chains and steps can still find their files!

development:
  environment: development
  file_location: <%= ENV.fetch('DEVELOPMENT_FILE_LOCATION', '') %>
test:
  environment: test
  file_location: <%= ENV.fetch('TEST_FILE_LOCATION', '') %>
production:
  environment: production
  file_location: <%= ENV.fetch('PRODUCTION_FILE_LOCATION', '') %>
