# If you are going to change this,
# you should move the contents of the old storage directory to the new one
# so that process chains and steps can still find their files!

development:
  environment: development
  file_location: ./ink_api_files
test:
  environment: test
  file_location: /tmp/ink_api_files/
production:
  environment: production
  file_location: ./ink_api_files/
