# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.


# Do not keep production secrets in the repository,
# instead read values from the environment.

from_environment: &deployable_settings
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  pusher_app_id: <%= ENV["SLANGER_APP_ID"] %>
  slanger_id: <%= ENV['SLANGER_ID'] %>
  slanger_key: <%= ENV['SLANGER_KEY'] %>
  slanger_secret: <%= ENV['SLANGER_SECRET'] %>
  slanger_host: <%= ENV['SLANGER_HOST'] || "localhost" %>
  slanger_port: <%= ENV['SLANGER_PORT'] || 4567 %>

production:
  <<: *deployable_settings
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  <<: *deployable_settings

development:
  <<: *deployable_settings
  secret_key_base: 818b79b884f3e0f14832641d50abd41426163ff5aefbda04ddf917701c621b524a1c4218fb098c61f937c8571edee7b4f121d472aa5c68c24342825d265589d5
  slanger_id: some_fake_string
  slanger_key: 44332211ffeeddccbbaa
  slanger_secret: aabbccddeeff11223344
  slanger_host: localhost
  slanger_port: 4567
  slanger_app_id: fakefakelol

test:
  <<: *deployable_settings
  secret_key_base: 83dcb9140c078bd7d5a381be700e34b99de33ddf1b5d7f92ba5df356afc7f419bcc605a978649c6d639fe100f05ff721a1a482a7c1e0df416d904eef7a1acee9

