# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
from_environment: &deployable_settings
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  slanger_app_id: <%= ENV["SLANGER_APP_ID"] %>
  slanger_id: <%= ENV["SLANGER_ID"] %>
  slanger_key: <%= ENV['SLANGER_KEY'] %>
  slanger_secret: <%= ENV['SLANGER_SECRET'] %>
  slanger_host: <%= ENV['SLANGER_HOST'] || "localhost" %>
  slanger_port: <%= ENV['SLANGER_API_PORT'] || 4567 %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>

development:
  <<: *deployable_settings
  secret_key_base: <%= ENV['DEVELOPMENT_SECRET_KEY_BASE'] %>


test:
  <<: *deployable_settings
  secret_key_base: <%= ENV['TEST_SECRET_KEY_BASE'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *deployable_settings
  secret_key_base: <%= ENV['DEVELOPMENT_SECRET_KEY_BASE'] %>